version: '3'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    user: root
    environment:
      - BITNAMI_DEBUG=false
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'docker.io/bitnami/phabricator:2020-debian-10'
    # use root container
    user: root
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PHABRICATOR_DATABASE_HOST=mariadb
      - PHABRICATOR_HOST=http://xuminhui.myqnapcloud.cn:10080
      - PHABRICATOR_USERNAME=
      - PHABRICATOR_PASSWORD=
      - PHABRICATOR_USE_LFS=yes
      - PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY=yes
    ports:
      - '10080:80'
      - '10022:22'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
